package fr.sauget.dsn.dsntoolbox.model.Rubriques;

public class NOMBRE_D_HEURE_SUPPLEMENTAIRE_OU_COMPLEMENTAIRE__D_EQUIVALENCE__D_HABILLAGE_ET_DE_DESHABILLAGE_211 extends Rubrique {

    final RubriqueType type = RubriqueType.NOMBRE_D_HEURE_SUPPLEMENTAIRE_OU_COMPLEMENTAIRE_D_EQUIVALENCE_D_HABILLAGE_ET_DE_DESHABILLAGE_211;
}
